### ISSUE TITLE
Insert/Merge SQL code

### ISSUE THREAD

**Issue by mpapan01** [epl362/web_services#21]
Insert SQL code (for database initialisation) and/or merge it.
I have added some SQL source in `maria_src1`.
There is also some source in Queries folder.

If you have any other SQL code you should add it and I will merge it.

**Comment by ppavli02** [comment]
I have just updated all the Query files! Please check it out!

**Comment by mpapan01** [comment]
Is it okay if we rename `condition` table  to `condition_`?
It is a reserved word, and it causes problems.

**Comment by mpapan01** [comment]
I think now it is okay.
BTW, please `git pull` because I 've made some changes regarding some `PrimaryKeys`!

When you do this, please close this issue!
